# serverless.yml

service: aws-serverless-application-anz

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
